### PR TITLE
Fix parsing of nested functions

### LINKED ISSUE #23: Wrong parsing of nested functions with arguments
Parsing a nested function with arguments followed by another DSN make the latter inside the argument of the former.

For example, this DSN:
```
foo(failover:(tcp://localhost:61616,tcp://remotehost:61616)?initialReconnectDelay=100 udp://localhost)?start=now`
```
gives:
```
^ Nyholm\Dsn\Configuration\DsnFunction^ {#110
  -name: "foo"
  -arguments: array:1 [
    0 => Nyholm\Dsn\Configuration\DsnFunction^ {#72
      -name: "failover"
      -arguments: array:2 [
        0 => Nyholm\Dsn\Configuration\Url^ {#85
          -host: "localhost"
          -port: 61616
          -path: null
          -scheme: "tcp"
          -parameters: []
          -authentication: array:2 [
            "user" => null
            "password" => null
          ]
        }
        1 => Nyholm\Dsn\Configuration\Url^ {#84
          -host: "remotehost"
          -port: 61616
          -path: null
          -scheme: "tcp"
          -parameters: []
          -authentication: array:2 [
            "user" => null
            "password" => null
          ]
        }
      ]
      -parameters: array:1 [
        "initialReconnectDelay" => "100 udp://localhost" <----------- PROBLEM HERE
      ]
    }
  ]
  -parameters: array:1 [
    "start" => "now"
  ]
}
```

It doesn't matter if we use a comma instead of a space to separate the two arguments of `foo()`.

### PR DESCRIPTION
**Pull request by chapa**
Fixes #23

Old regex: https://regex101.com/r/dxVIlH/1
New regex: https://regex101.com/r/FdUxa1/1

### CODE REVIEW

**Comment by chapa** [comment]
@Nyholm did you see this?

**Comment by Nyholm** [comment]
Hey. 
Thank you for the ping. I must have missed this. 

Wow, well done adding the tests and deconstruct this issue. I added another commit to trigger the CI. The tests are passing. I'll handle the unrelated red jobs in a different PR. 

Thank you

**Comment by Nyholm** [comment]
Could you confirm this is working before we tag a release?

**Comment by chapa** [comment]
You're very welcome.
Yes I confirm this is working now, thank you!

**Comment by Nyholm** [comment]
Awesome!
I'll tag a release now

**Pull request merged**
